sudo: required
language: python
services:
  - docker

env:
  global:
    - REGISTRY_USER=jamiehewland
    - secure: "4qDsmFNSiMYOmAsDugOEsTxOJIszKtMUqiymNWsWyNq1MYDRsRzILtfAAxHo1V6Bva2JfCKwQu6PRu53kW6SvgIZhtcVD33qx/fhGGXa4izZO3E2znSLJ2x15iO8Py/4OHkMWEG+y/HLh4sDWhEQEM25mGrcYywc0iBIWnmezQ2yOH2ow3MlMTQ+Eu3vDWmD4CyDJU/fmAx9rU38xzYK1mksiSgjPC0xsM3ZLsbIiEXXhTZzgwJvrBfVaEMosO2ZI3dYeVEe0v0eaMPT9Sh2prQqsNUJrIWQQpzLQB4g/ORUddj96LbJ0lplsJgJ9f86xN0F4wEoc0aEea8tSMjXEnxatQi4nwXRXm0HbC2K4/rMqqTbn5PBi3pMtS4k02lxvysJyaaaMc0cjE4ZiQsSPlYEmxet1gaJbM+PGDCvvTfuPaDTwbWWZLslHkxdriAZhI5pKl2++hjm1/HP88cY1YWOIBW7fW+wawyApATfznPKVzdoyLapHc+hLsVVU/rB8QHTWMEjpLAGVjZpHwYYyidZngbIAnzRxBt0LyJJnHSO5jGgIrtkgJbtwdCgNVaAGCcZ9a+bwQWNuSxPC2d4tLufpqbMEXMujKG3YPyrQ6/80MRqdKa1TBZwwnsOWfjSwZe+7i9wxBz1gR6KegLMOCuMAslcCxA+BoaezH2cbPY="
  matrix:
    - VERSION=2 VARIANT=
    - VERSION=2 VARIANT=slim

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" -y docker-engine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$(awk '$1 == "FROM" { print $2; exit }' $VERSION/onbuild/Dockerfile)${VARIANT:+-$VARIANT}"
  - version="$(awk '$2 == "PYPY_VERSION" { print $3; exit }' $VERSION/Dockerfile)"
  - echo "Building image $image with PyPy $VERSION version $version"

script:
  - docker build -t "$image" "$VERSION${VARIANT:+/$VARIANT}"
  # Run the "official-images" tests, but first tag our image like the official
  # ones to get the same tests
  - |
    official_image="pypy:$VERSION${VARIANT:+-$VARIANT}"
    docker tag "$image" "$official_image"
    ~/official-images/test/run.sh "$official_image"
  # the "onbuild" variant has to happen with the base variant because it's FROM it
  - if [ -z "$VARIANT" ]; then docker build -t "${image}-onbuild" "$VERSION/onbuild"; fi

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: ./deploy.py "$image" "$version" && if [ -z "$VARIANT" ]; then ./deploy.py "${image}-onbuild" "$version"; fi
  on:
    branch: develop
