sudo: required
language: python
services:
  - docker

env:
  global:
    - REGISTRY_USER=jamiehewland
    - secure: "63Oz7ALcHGl2R9XmssiHqZzgD7XPgK4XsqwCw0lecdEyYde7cYkvapzybW38kF09lX0QL0WmaPVLqVGoFmOLeE83pkTZ6UUqFX0NgxJbH9hP/Ghg5NngtVELZUmkHNF8odtx/SmolVbt1utyxHBROgGjyLdUFqZxMVOqb/gEk9MClzCsam6lLB5Wn+cK/CdNFwm4fYlLpA+5Nj9qudSqRCEuCk9dtyzzq/rfwBhfMpG8po1Y3d++7sZ4RxE+5y//4n+cQZSfmd0O8jnsdk1ESsF7sUr9R2zpNkz3BZLsPC3F2BGIc/84fax3/6k6dlzvdIRHYgpspynAWS/Ui06Sbzr7lHD7zO/bdjmgdUTcLmmqf7qpWEETWrELUYX7+ljtvdJnAxbz/5z97pep4OC5g2V7P/n9sHWa7xzSCD4F3cYoL+i5aU9SqX9WTO4zgFC4ajcpE/tRDD4WzFXQ/MVSUCRUubyi7bU8PdlgITT658pWK0Su3/OWQ7Fb/gZO7w+8bGexj/vC//i+3almojVW2Xk9ad3+vIy5Ej0QhCLMl7fdYhGd5CtNllnCAHp8P3DBLfpgy4zJRNkdl1BMw+ZfW4FRA60QCqBj3QN2TquLz3bROjDtnclvhN1QZJaW/lIufm9HbHkKfQ1tvNyeYwUlJ0gNH5QYgCKR+NWj+tacQPU="
  matrix:
    - VERSION=2 VARIANT=
    - VERSION=2 VARIANT=slim

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" -y docker-engine

script:
  - ./build.sh

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: develop
